name: Test Secrets

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test SSH connection
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSK_KEY }}
        script: |
          echo "✅ Secrets work! Connected to $(hostname)"
          docker ps
